let data = [
  {
    id : 'HO00002396',
    name : '578: PHÁT ĐẠN CỦA KẺ ĐIÊN',
    description: 'Cuộc sống của hai cha con người lái xe container trên chiếc xe vàng cứ êm đềm diễn ra cho đến ngày cô bé xa cha đi học. Mọi thứ bổng đảo lộn khi người cha nhận được tin cô con gái của mình bị trầm cảm nặng.',
    age:'C18 - PHIM DÀNH CHO KHÁN GIẢ TỪ 18 TUỔI TRỞ LÊN',
    producer: 'Lương Đình Dũng',
    actor: 'H\'hen Niê, Hoàng Phúc, Ngọc Tình, Tuấn "Hạc"',
    category: 'action',
    public: '2022-02-22',
    time: '106 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002396.jpg',
    embed: 'https://www.youtube.com/embed/cRktvGSDpuE'
  },
  {
    id : 'HO00002414',
    name : 'SPACE DOGS: TROPICAL ADVENTURE',
    description: 'Khi một xoáy nước bí ẩn xuất hiện ở vùng Đại Tây Dương, các phi hành gia Belka và Strelka được cử đến để điều tra. Với sự giúp đỡ của những người bạn tốt của họ, Belka và Strelka một lần nữa phải hành động để giải cứu hành tinh của họ',
    age:'P - PHIM PHỔ BIẾN CHO MỌI LỨA TUỔI',
    producer: 'Inna Evlannikova',
    actor: 'Mauriett Chayeb, Paula Andrea Barros, Clay Montgomery Cartland',
    category: 'Animation',
    public: '2022-04-22',
    time: '80 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002414.jpg',
    embed: 'https://www.youtube.com/embed/P39r6XDvkiA'
  },
  {
    id : 'HO00002416',
    name : 'NGHỀ SIÊU DỄ',
    description: 'Phim kể về một cảnh sát đã nghỉ hưu cùng các thanh niên "bất hảo" mua lại 1 quán ăn để làm nơi theo dõi tên trùm tội phạm. Tuy nhiên, quán bất ngờ nổi tiếng khiên cho phi vụ có nguy cơ đổ bể.',
    age: 'P - PHIM PHỔ BIẾN CHO MỌI LỨA TUỔI',
    producer: 'VO THANH HOA',
    actor: 'THU TRANG, KIEU MINH TUAN, HUỲNH PHƯƠNG',
    category: 'Action',
    public: '2022-04-29',
    time: '113 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002416.jpg',
    embed:'https://www.youtube.com/embed/Nm0ImwyPaVE'
  },
  {
    id : 'HO00002417',
    name : 'CHICKEN HARE AND THE HAMSTER OF DARKNESS',
    description: 'Với cốt truyền đầy hài hước, hành động và bối cảnh hoành tráng Chickenhare And The Hamster là bộ phim hoạt hình phiêu lưu hoàn hảo dành cho gia đình dịp Hè 2022 này.',
    age: 'P - PHIM PHỔ BIẾN CHO MỌI LỨA TUỔI',
    producer: 'Ben Stassen, Benjamin Mousquet',
    actor: 'Danny Fehsenfeld, Mark Irons',
    category: 'Animation',
    public: '2022-04-29',
    time: '91 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002417.jpg',
    embed: 'https://www.youtube.com/embed/w-P8nVYlXEs'
  },
  {
    id : 'HO00002421',
    name : 'SONIC: THE HEDGEHOG 2',
    description: 'Khi Robotnik tìm cách quay trở về Trái Đất thành công, ông ta có một đồng minh mới là Knuckles hùng mạnh, liệu Sonic và người bạn ới Tails có thể ngăn chặn được âm mưu điên rồi để cứu lấy thế giới?',
    age: 'P - PHIM PHỔ BIẾN CHO MỌI LỨA TUỔI',
    producer: 'Jeff Fowler',
    actor: 'Ben Schwartz, James Marsden, Colleen O\'Shaughnessey',
    category: 'Animation',
    public: '2022-04-15',
    time: '122 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002421.jpg',
    embed: 'https://www.youtube.com/embed/47r8FXYZWNU'
  },
  {
    id : 'HO00002422',
    name : 'DOCTOR STRANGE',
    description: 'Stephen Strange sử dụng một phép thuật bị cấm mở ra cánh cửa đến đa vũ trụ, với sự giúp đỡ của các đồng minh thần bí cả cũ và mới, vượt qua thực tại để đối đầu với 1 kẻ thù mới, bí ẩn ,nguy hiểm và đáng sợ hơn',
    age: 'C13 - PHIM DÀNH CHO KHÁN GIẢ TỪ 13 TUỔI TRỞ LÊN',
    producer: 'Sam Raimi',
    actor: 'Benedict Cumberbatch, Rachel McAdams, Elizabeth Olsen',
    category: 'Action',
    public: '2022-05-04',
    time: '128 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002422.jpg',
    embed: 'https://www.youtube.com/embed/aWzlQ2N6qqg'
  },
  {
    id : 'HO00002425',
    name : 'KẺ THỨ BA',
    description: 'Phim là câu chuyện về mối tình thơ mộng, lãng mạn.Tuy nhiên, lúc hạnh phúc vừa chớm nở thì biến cố lại bất ngờ ập đến. Một tai nạn giao thông nghiêm trọng, ảnh hưởng đến tính mạng đã xảy ra, đúng lúc lời thoại “tình yêu và cái chết luôn đi liền với nhau”',
    age: 'C16 - PHIM DÀNH CHO KHÁN GIẢ TỪ 16 TUỔI TRỞ LÊN',
    producer: 'Park Hee Jun',
    actor: 'Han Jae Suk, Ly Nha Ky',
    category: 'Romance',
    public: '2022-05-13',
    time: '84 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002425.jpg',
    embed: 'https://www.youtube.com/embed/5FhTtLUVS1k'
  },
  {
    id : 'HO00002430',
    name : 'FIRE STARTERS',
    description: 'Phim kể về một cô gái trẻ cố gắng hiểu làm thế nào cô ấy có được sức mạnh để đốt cháy mọi thứ bằng tâm trí của mình một cách bí ẩn.',
    age:'C18 - PHIM DÀNH CHO KHÁN GIẢ TỪ 18 TUỔI TRỞ LÊN',
    producer: 'Keith Thomas',
    actor: 'Zac Efron, Ryan Kiera Armstrong, Kurtwood Smith',
    category: 'Horror',
    public: '2022-05-13',
    time: '95 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002430.jpg',
    embed: 'https://www.youtube.com/embed/59MJfJPP5eo'
  },
  {
    id : 'HO00002431',
    name : 'THE ANCHOR',
    description: 'Se-Ra là một người dẫn chương trình nổi tiếng. 5 phút trước khi chương trình của cô ấy được phát trực tiếp, cô ấy nhận được một cuộc điện thoại, Người gọi Mi-So nói với Se-Ra "Tôi sắp bị ai đó giết. Xin hãy che đậy câu chuyện về cái chết của tôi."',
    age:'C18 - PHIM DÀNH CHO KHÁN GIẢ TỪ 18 TUỔI TRỞ LÊN',
    producer: 'Ji-Yeon Jung',
    actor: 'Woo-hee Chun, Shin Ha-kyun, Lee Hye-yeong',
    category: 'Mystery',
    public: '2022-05-20',
    time: '111 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002431.jpg',
    embed: 'https://www.youtube.com/embed/9MtrvAPLg2w'
  },
  {
    id : 'HO00002432',
    name : 'SHARK BAIT',
    description: 'Một nhóm bạn đang tận hưởng kỳ nghỉ cuối tuần. Họ phải vật lộn để tìm đường về nhà với một người bạn bị thương nặng trong khi từ vùng nước bên dưới những kẻ săn mồi ẩn nấp.',
    age:'C16 - PHIM DÀNH CHO KHÁN GIẢ TỪ 16 TUỔI TRỞ LÊN',
    producer: 'James Nunn',
    actor: 'Holly Earl, Jack Trueman, Catherine Hannay',
    category: 'Thriller',
    public: '2022-04-19',
    time: '85 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002432.jpg',
    embed: 'https://www.youtube.com/embed/aLjKgremu9Q'
  },
  {
    id : 'HO00002434',
    name : 'URBAN MYTHS',
    description: 'Tuyển tập truyền thuyết đô thị Seoul - khi những địa điểm, đồ vật quyen thuộc xung quanh chúng ta lại ẩn chứa những bí ẩn kinh hoàng khiến việc tồn tại ở hiện thực còn khiếp sợ hơn cái chết.',
    age:'C18 - PHIM DÀNH CHO KHÁN GIẢ TỪ 18 TUỔI TRỞ LÊN',
    producer: 'Hong Won Ki',
    actor: 'HaiDepTrai',
    category: 'Horror',
    public: '2022-04-19',
    time: '122 phút',
    language: 'Phụ đề tiếng Việt',
    image: 'HO00002434.jpg',
    embed: 'https://www.youtube.com/embed/UreydwjeHbU'
  },
];